### PR TITLE
Finish init Project and setup CI

### PR DESCRIPTION
**Pull request by lunguyendev**

### CODE REVIEW

**Comment by lunguyendev** [comment]
ready

**Comment by lunguyendev** [comment]
ready

**Comment by thanhlong-dev** [comment]
x-special/nautilus-clipboard
copy
file:///home/thanhlong/Pictures/Screenshot%20from%202020-10-22%2011-03-04.png

**Comment by lunguyendev** [comment]
Screenshot from 2020-10-22 11-03-04

**Comment by vanvtt-0952** [comment]
merged

**Pull request merged**
